flask_app/project/discussion/views.py
#Authors: Tamim Nasir
#Coding: utf-8

#################
#### imports ####
#################
 
from flask import render_template, Blueprint, request, flash, redirect, url_for
from flask_login import LoginManager, login_required, login_user, current_user, logout_user
from .Forms import AddComment
from project.models import Discussion, Forum, User
from project import db

################
#### config ####
################
 
discussion_blueprint = Blueprint('discussion', __name__)
 
 
################
#### routes ####
################
@discussion_blueprint.route('/discussion/<forum_id>')
def discussion(forum_id):
    discussions = db.session.query(Discussion, User).join(User).filter(Discussion.forum_id == forum_id).order_by(Discussion.id.asc())
    forum_infos = db.session.query(Forum, User).join(User).filter(Forum.id == forum_id)
    return render_template('discussion.html', discussions=discussions, forum_infos=forum_infos, forum_no=forum_id)

@discussion_blueprint.route('/AddComment/<forum_id>', methods=['POST'])
@login_required
def add_comment(forum_id):
    form = AddComment()
    if request.method == 'POST':
        new_comment = Discussion(form.comment.data, forum_id, current_user.id)
        db.session.add(new_comment)
        db.session.commit()
        return discussion(forum_id)
        # return render_template('forum.html', message='greate success')

flask_app/project/forums/views.py
#Authors: Tamim Nasir
#Coding: utf-8

#################
#### imports ####
#################
 
from flask import render_template, Blueprint, request, flash, redirect, url_for
from flask_login import LoginManager, login_required, login_user, current_user, logout_user
from .Forms import AddTopic
from project.models import Forum, User
from project import db

################
#### config ####
################
 
forums_blueprint = Blueprint('forums', __name__)
 
 
################
#### routes ####
################
@forums_blueprint.route('/forums')
def forum():
    # all_forums = Forum.query.all()
    all_forums = db.session.query(Forum, User).join(User).order_by(Forum.id.desc())
    return render_template('forum.html', all_forums=all_forums)

@forums_blueprint.route('/addTopic', methods=['POST'])
@login_required
def add_topic():
    form2 = AddTopic()
    if request.method == 'POST':
        new_topic = Forum(form2.question_title.data, form2.main_question.data, current_user.id)
        db.session.add(new_topic)
        db.session.commit()

        return forum()

flask_app/project/recipes/views.py
#Authors: Leo M. Holm & Axel Holm
#Coding: utf-8


#### imports ####

 
from flask import render_template, Blueprint, request, flash, redirect, url_for, jsonify
from project.models import Recipe, User, Ingredient, IngredientSchema, RecipeHasIngredient
from .Forms import AddRecipeForm
from project import db, images
from flask_login import LoginManager, login_required, login_user, current_user, logout_user
from flask_uploads import UploadSet, IMAGES, configure_uploads



#### config ####

 
recipes_blueprint = Blueprint('recipes', __name__) 


#### routes ####

@recipes_blueprint.route('/')
def index():
    all_public_recipes = Recipe.query.filter_by(is_public=True)
    return render_template('index.html', public_recipes=all_public_recipes)

@recipes_blueprint.route('/public')
def public_recipes():
    all_public_recipes = Recipe.query.with_entities(Recipe.id, Recipe.recipe_title, Recipe.recipe_description).filter_by(is_public=True)
    return render_template('public_recipes.html', public_recipes=all_public_recipes)

@recipes_blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add_recipe():
    form = AddRecipeForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            filename = images.save(request.files['recipe_image'])
            url = images.url(filename)
            new_recipe = Recipe(form.recipe_title.data, form.recipe_description.data, current_user.id, form.is_public.data, filename, url)
            db.session.add(new_recipe)
            db.session.commit()

            # Lägg in varje ingrediens för recepete genom att loopa igenom det som skickades från formuläret
            for ingredient in request.form.getlist("ingredient[]"):
                ing = ingredient.split("-")
                ingredient_id = ing[0]
                quantity = ing[1]
                new_recipe_ingredient = RecipeHasIngredient(new_recipe.id, ingredient_id, quantity)
                db.session.add(new_recipe_ingredient)
                db.session.commit()
                
                



            flash('New recipe, {}, added!'.format(new_recipe.recipe_title), 'success')
            return redirect(url_for('recipes.user_recipes'))
        else:
            #flash_errors(form)
            flash('ERROR! Recipe was not added.', 'error')
    else:
        
        return render_template('add_recipe.html', form=form)

@recipes_blueprint.route('/ingredientlist', methods=['GET'])
@login_required
def get_ingredients():
    ingredient_list = Ingredient.query.all()
    ingredient_schema = IngredientSchema(many=True)
    output = ingredient_schema.dump(ingredient_list)
    return jsonify({'ingredients' : output})

@recipes_blueprint.route('/recipes')
@login_required
def user_recipes():
    all_user_recipes = Recipe.query.filter_by(user_id=current_user.id)
    return render_template('user_recipes.html', user_recipes=all_user_recipes)

@recipes_blueprint.route('/edit/<recipe_id>', methods=['GET', 'POST'])
@login_required
def edit_recipe(recipe_id):
    form = EditRecipeForm(active=True)
    recipe_with_user = db.session.query(Recipe, User).join(User).filter(Recipe.id == recipe_id).first()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.recipe_image.data is not None:
                filename = images.save(request.files['recipe_image'])
                url = images.url(filename)
            
            else:
                filename = recipe_with_user.Recipe.image_filename
                url = recipe_with_user.Recipe.image_url

            uppdate = Recipe.query.filter_by(id=recipe_id).first()
            uppdate.recipe_title = form.recipe_title.data 
            uppdate.recipe_description = form.recipe_description.data 
            uppdate.is_public = form.is_public.data
            uppdate.image_filename = filename
            uppdate.image_url = url
            db.session.commit()
            flash('Recept, {}, har ändrats!'.format(uppdate.recipe_title), 'success')
            return redirect(url_for('recipes.user_recipes'))

        else:
            #flash_errors(form)
            flash('ERROR! Recipe was not added.', 'error')

    return render_template('edit_recipe.html', form=form, recipe=recipe_with_user, recipe_id=recipe_id)

@recipes_blueprint.route('/recipe/<recipe_id>')
def recipe_details(recipe_id):
    recipe_with_user = db.session.query(Recipe, User).join(User).filter(Recipe.id == recipe_id).first()
    ingredients_for_recipe = db.session.query(Ingredient, RecipeHasIngredient.quantity).join(RecipeHasIngredient).filter(RecipeHasIngredient.recipe_id == recipe_id).all()
    results = ingredients_for_recipe
    
    if recipe_with_user is not None:
        if recipe_with_user.Recipe.is_public:
            return render_template('recipe_detail.html', recipe=recipe_with_user, ingredients=results)
        else:
            if current_user.is_authenticated and recipe_with_user.Recipe.user_id == current_user.id:
                return render_template('recipe_detail.html', recipe=recipe_with_user, ingredients=results)
            else:
                flash('Error! Incorrect permissions to access this recipe.', 'error')
    else:
        flash('Error! Recipe does not exist.', 'error')
    return redirect(url_for('recipes.public_recipes'))

@recipes_blueprint.route('/video')
def videos():
    return render_template('video.html')

@recipes_blueprint.route('/video/<video_id>')
def videoplayer(video_id):
    return render_template('video_player.html', video_id=video_id)

@recipes_blueprint.route('/media')
def media():
    recipe_image = db.session.query(Recipe.image_url, Recipe.image_filename).all()
    return render_template('media.html', images=recipe_image)

flask_app/project/users/views.py
#Authors: Leo M. Holm & Axel Holm
#Coding: utf-8


#### imports ####

from flask import Flask, render_template, Blueprint, request, flash, redirect, url_for, abort
from project import db #, mail
from .Forms import RegisterForm, LoginForm, change_emailForm, change_usernameForm, change_passwordForm
from project.models import User, Recipe
from sqlalchemy.exc import IntegrityError
from flask_login import LoginManager, login_required, login_user, current_user, logout_user
from datetime import datetime
#from flask_mail import Mail, Message


#### config ####


users_blueprint = Blueprint('users', __name__)


#### routes ####


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.username.data, form.email.data, form.password.data)
                new_user.authenticated = True
                new_user.last_logged_in = new_user.current_logged_in
                new_user.current_logged_in = datetime.now()
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)

                # send_confirmation_email(new_user.email)

                flash('Tack, du är nu registrerad!', 'success')
                return redirect(url_for('recipes.public_recipes'))
                
            except IntegrityError:
                db.session.rollback()
                flash('Fel! Emailen ({}) finns redan.'.format(form.email.data), 'error')
    return render_template('register.html', form=form)

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                user.last_logged_in = user.current_logged_in
                user.current_logged_in = datetime.now()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Thanks for logging in, {}'.format(current_user.email))
                return redirect(url_for('recipes.public_recipes'))
            else:
                flash('Oj, någonting i dina uppgifter var fel!', 'error')
    return render_template('login.html', form=form)

@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Välkommen tillbaka!', 'info')
    return redirect(url_for('users.login'))

@users_blueprint.route('/user_profile')
@login_required
def user_profile():
    all_user_recipes = Recipe.query.filter_by(user_id=current_user.id)
    return render_template('user_profile.html', user_recipes=all_user_recipes)

@users_blueprint.route('/admin_view_users')
@login_required
def admin_view_users():
    if current_user.role != 'admin':
        abort(403)
    else:
        users = User.query.order_by(User.id).all()
        return render_template('admin_view_users.html', users=users)
    return redirect(url_for('stocks.watch_list'))


@users_blueprint.route('/change_username', methods=['GET','POST'])
@login_required
def change_username():
    form = change_usernameForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_username = (form.username.data)
            stm = User.query.filter_by(id=current_user.id).first()
            stm.username = new_username
            db.session.commit()
            flash('Användar namnet har ändrats till {}'.format(new_username), 'info')
            return redirect(url_for('users.user_profile'))

    return render_template('change_username.html', form=form )


@users_blueprint.route('/change_email', methods=['GET','POST'])
@login_required
def change_email():
    form = change_emailForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            if user is not None and user.is_correct_password(form.password.data):
                new_email = (form.email.data)
                stm = User.query.filter_by(id=current_user.id).first()
                stm.email = new_email
                db.session.commit()
                flash("Email adresen har ändrats till {}".format(new_email), 'info')
                return redirect(url_for('users.user_profile'))

    return render_template('change_email.html', form=form)

@users_blueprint.route('/change_password', methods=['GET','POST'])
@login_required
def change_password():
    form = change_passwordForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            if user is not None and user.is_correct_password(form.password.data):
                new_password = form.new_password.data
                stm = User.query.filter_by(id=current_user.id).first()
                stm.password = new_password
                #db.session.commit()
                flash("Lösenordet har ändrats", 'info')
                return redirect(url_for('recipes.user_profile'))
                 
    return render_template('change_password.html', form=form)

flask_app/project/templates/410.html
<!--Authors:Leo.M.H&Axel.H | Coding: utf-8-->
<!-- Page for removed content 410 -->

{% extends "layout.html" %}
 
{% block content %}
 
  <h1>Pouff</h1>
  <h4>Det du letar efter finns inte längre och lär inte komma tillbaka!</h4>
  <h4><a href="{{ url_for('recipes.index') }}">Akademi Gastrologi</a></h4>
 
{% endblock %}

flask_app/project/templates/_form_macros.html
<!--Authors:Leo.M.H&Axel.H | Coding: utf-8-->
<!-- Macro for errormessages and rendering fields -->

{% macro render_field(field) %}
 
 
<dt>{{ field.label }}:
 
<dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
</dd>
 
 
{% endmacro %}

flask_app/project/templates/add_recipe.html
<!--Authors:Leo.M.H&Axel.H | Coding: utf-8-->

{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}



<!--This shows within the layout.html template-->
<div>
  <img src="../static/images/pig.png" alt="pig" style="height: 20%;width: 20%;float: right;padding-top: 100px;padding-left: 15px;margin-right: 200px;">
</div>

<div class="container">
  <div class="add-recipe">
    <div class="page-header">
      <h2>Lägg till ett nytt recept</h2>
    </div>
    <!-- Form to blueprint with data sent -->
    <form action="{{ url_for('recipes.add_recipe', ingredients=ingredients) }}" method="post" enctype="multipart/form-data">
      {{ form.csrf_token }}
      <dl>
        {{ render_field(form.recipe_title, placeholder="Titel på recept") }}
        {{ render_field(form.recipe_description, placeholder="Beskrivning av recept") }}
        <br>
        <p><strong>Ingredienser:</strong></p>
        <!--Add new ingredient inputs-->
        <div class="add_new_recipes" id="add_new_recipe">
            <select class="ingredients_select" name="ingredient_select"></select>
            <input type="text" class="ingredient_amount"/>
            <span class="unit_label measurement_unit_label"></span>
            <input type="hidden" name="ingredient[]" class="hidden-ingredient-input">
        </div>
        <br>
        <!-- Add new ingredient button-->
        <button id="clone_ingredient" >Lägg till en till ingrediens</button>
        
        <br></br>
        
        {{ render_field(form.recipe_image) }}
        <br>
        {{ render_field(form.is_public) }}
      </dl>
      <!-- Button for submitting recipe-->
      <button class="btn btn-sm btn-success" type="submit">Lägg till recept</button>
    </form> 
  </div>
</div>

<script>
  
  $(document).ready(function() {
    /* Collect values and text on change from fields */
    $("body").on("change",".ingredients_select, .ingredient_amount", function() {
      let ingredientId = $(this).parent().children(".ingredients_select").val();
      let amount = $(this).parent().children(".ingredient_amount").val();
      let unit = $(this).parent().children(".unit_label").text();

      /* Add values and text to hidden input */
      let inputValue = ingredientId + "-" + amount + "-" + unit;
      $(this).parent().children(".hidden-ingredient-input").val(inputValue);
    });
    
    /* Clone new ingredient from last */
    $("#clone_ingredient").on("click", function(){
      let new_ingredient = $('.add_new_recipes:last').clone(true);
      $(new_ingredient).insertAfter(".add_new_recipes:last");
    });

    /* Clone with default value for new ingredient */
    $("#clone_ingredient").on("click", function(event){
      event.preventDefault();
    });
    
    /* Get ingredient list */
    $.getJSON($SCRIPT_ROOT + "/ingredientlist", null, function(data) {
      const ingredients = data.ingredients

      /* Populate select */
      $.each(ingredients, function(index, item){
        $(".ingredients_select").append(
          $("<option></option>")
            .text(item.name)
            .val(item.id)  
        )
      });


      /* Ingredients select handler */
      function on_ingredients_select_change(event) {
        const selected_ingredient_id = event.target.value

        const ingredient = ingredients.find(function(current_ingredient) {  
          return current_ingredient.id == selected_ingredient_id
        })
        /* Add measurement_label */
        $(".measurement_unit_label:last").text(ingredient.measurement_unit)
        
        
      };
      
      /* On change run function for id match*/
      $(".ingredients_select").change(on_ingredients_select_change)


    }) 
  });


</script>

{% endblock %}

flask_app/project/templates/change_email.html
<!--Author: Anton Hellberg | Coding: utf-8-->

{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
<!--This shows within the layout.html template-->
<div>
  <img src="../static/images/pig.png" alt="pig" style="height: 20%;width: 20%;float: right;padding-top: 100px;">
  <img src="../static/images/grains.png" alt="grains" style="height: 10%;width: 10%;float: left;padding-top: 215px;">
  <img src="../static/images/kebab.png" alt="kebab" style="height: 10%;width: 10%;float: left;padding-top: 75px;">
</div>
<div class="container">
<div class="user-registration">
  <div class="page-header">
    <h2>Byt email</h2>
  </div>
<!-- Form for changing email -->
<form action="{{ url_for('users.change_email') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.password, placeholder="Lösenord") }}
      {{ render_field(form.email, placeholder="Ny Email") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Byt email</button>
  </form>
</div>
</div>  
{% endblock %}

flask_app/project/templates/change_password.html
<!--Author: Anton Hellberg | Coding: utf-8-->

{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
<!--This shows within the layout.html template-->
<div>
  <img src="../static/images/pig.png" alt="pig" style="height: 20%;width: 20%;float: right;padding-top: 100px;">
  <img src="../static/images/grains.png" alt="grains" style="height: 10%;width: 10%;float: left;padding-top: 215px;">
  <img src="../static/images/kebab.png" alt="kebab" style="height: 10%;width: 10%;float: left;padding-top: 75px;">
</div>
<div class="container">
<div class="user-registration">
  <div class="page-header">
    <h2>Byt lösenord</h2>
  </div>
<form action="{{ url_for('users.change_password') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.password, placeholder="Ditt Gamla Lösenord") }}
      {{ render_field(form.new_password, placeholder="Nytt Lösenord") }}
      {{ render_field(form.confirm, placeholder="Bekräfta lösenord") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Byt lösenord</button>
  </form>
</div>
</div>  
  
{% endblock %}

flask_app/project/templates/discussion.html
{% extends "layout.html" %}
{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/forums">Forum</a></li>
            <li class="breadcrumb-item active" aria-current="page">Discussion</li>
        </ol>
    </nav>
    <main>
        <div class="container">
            {%for forum in forum_infos%}
            <div class="page-header">
                <h2>{{forum.Forum.forum_title}}</h2>
            </div>
            <!--Question-->
            <div class="row">
                <div class="col-xl question">
                    <div class="q_info">
                        <div class="row">
                            <div class="col-xs-3 col-sm-2 col-lg-1">
                                <div class="profile_img"></div>
                            </div>
                            <div class="col-xs-9 col-sm-10 col-lg-11">
                                <div class="row">
                                    {{forum.User.username}}
                                </div>
                                <div class="row">
                                    {{forum.Forum.created.strftime("%A %B %d, %Y, %I:%M:%S %p")}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="q_content">
                        {{forum.Forum.forum_description}}
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <h5>Leave a comment</h5>
            </div>
            <div class="row">
                <form action="{{ url_for('discussion.add_comment', forum_id=forum_no) }}" method="post">
                    <textarea class="myinput" name="comment" id="comment" cols="60" rows="1"></textarea>
                    <input type="submit" value="Submit">
                </form>
            </div>
            {% if discussions %}
            <div class="row">
                <h5>Answers</h5>
            </div>
            <!-- Answers -->

            <div class="row">
                {%for discussion in discussions%}
                <div class="answers">
                    <div class="row">
                        <div class="col-xs-3 col-sm-2 col-lg-1">
                            <div class="profile_img"></div>
                        </div>
                        <div class="col-xs-9 col-sm-10 col-lg-11">
                            <div class="row">
                                {{discussion.User.username}}
                            </div>
                            <div class="row">
                                {{discussion.Discussion.created.strftime("%A %B %d, %Y, %I:%M:%S %p")}}
                            </div>
                        </div>
                    </div>
                    {{discussion.Discussion.comment}}
                </div>
                {% endfor %}
            </div>
            {% endif %}

        </div>
    </main>
    <!-- Footer -->

{% endblock %}

flask_app/project/templates/edit_recipe.html
<!--Author: Anton Hellberg | Coding: utf-8-->

{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
<!--This shows within the layout.html template-->

<div class="container">
  <div class="add-recipe">
    <div class="page-header">
      <h2>Redigera recept</h2>
    </div>
    <form action="{{ url_for('recipes.edit_recipe', recipe_id=recipe_id) }}" method="post" enctype="multipart/form-data">
      {{ form.csrf_token }}
      <dl>
        {{ render_field(form.recipe_title, value=recipe.Recipe.recipe_title) }}
        {{ render_field(form.recipe_description, value= recipe.Recipe.recipe_description) }}
        {{ render_field(form.recipe_image) }}
        <p><b>Nuvarande bild:</b></p>
        <img src="{{ recipe.Recipe.image_url }}" alt="{{ recipe.Recipe.image_filename }}" height="200" width="200"> 
        {{ render_field(form.is_public) }}
      </dl>
      <button class="btn btn-sm btn-success" type="submit">Redigera recept</button>
    </form> 
  </div>
</div>
  
{% endblock %}

flask_app/project/templates/layout.html
<!--ALL FOLLOWING IS THE LAYOUT FOR EVERY PAGE IN USE including navbars, footer and flash messages for success and errors-->
<!--Authors:Leo.M.H&Axel.H&Tamim.N | Coding: utf-8-->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Akademi Gastrologi">
  <meta name="author" content="Leo.M.H., Axel.H, Anton.H & Tamim.N">
  <title>Akademi Gastrologi</title>

  <!-- styles -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/static/style.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type=text/javascript>
    $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
  </script>
</head>

<body>

  <!-- Static navbar -->
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">

      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
          data-target="#recipes-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-left"><img src="../static/images/logowhite.png" id="navbarlogo"></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="recipes-navbar-collapse-1">
        <ul class="nav navbar-nav">
          {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('recipes.user_recipes') }}">Mina recept</a></li>
          <li><a href="{{ url_for('recipes.public_recipes') }}">Alla recept</a></li>
          <li><a href="{{ url_for('recipes.add_recipe') }}">Lägg till recept</a></li>
          <li><a href="{{ url_for('recipes.videos') }}">Matlagningsutbildning</a></li>
          <li><a href="{{ url_for('recipes.media') }}">Galleri</a></li>
          <li><a href="{{ url_for('forums.forum') }}">Forums</a></li>
          {% if current_user.role == "admin" %}
          <li><a href="{{ url_for('users.admin_view_users') }}">View Users (Admin)</a></li>
          {% endif %}
          {% else %}
          <li><a href="{{ url_for('recipes.public_recipes') }}">Alla recept</a></li>
          <li><a href="{{ url_for('users.register') }}"><span class="glyphicon glyphicon-user"></span> Registrera
              dig</a></li>
          <li><a href="{{ url_for('users.login') }}"><span class="glyphicon glyphicon-log-in"></span> Logga in</a></li>

          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('users.user_profile') }}"><span class="glyphicon glyphicon-home"></span>
              {{current_user.username}}</a></li>
          <li><a href="{{ url_for('users.logout') }}"><span class="glyphicon glyphicon-log-out"></span> Logga ut</a>
          </li>
          {% else %}
          <li><a href="#">Welcome!</a></li>
          {% endif %}
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div><!-- /.container -->
  </nav>

  <div class="container-flash">
    <div class="content">

      <!-- flash messages for success, errors and info -->
      {% for error_message in get_flashed_messages(category_filter=["error"]) %}

      <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>

      {% endfor %}

      {% for success_message in get_flashed_messages(category_filter=["success"]) %}

      <div class="alert alert-success alert-dismissible">{{ success_message }}</div>

      {% endfor %}

      {% for info_message in get_flashed_messages(category_filter=["info"]) %}

      <div class="alert alert-info alert-dismissible">{{ info_message }}</div>

      {% endfor %}



    </div>
  </div>
  <!-- child template -->
  {% block content %}
  {% endblock %}
  <div class="footer">
    <p>Akademi Gastrologi - 2020</p>
  </div>

  </div><!-- /.container -->

  <!-- scripts -->
  <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
    integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
    crossorigin="anonymous"></script>
</body>

</html>